export const ROUTES = {
    LOGIN: '/login',
    DASHBOARD: '/',
    STAFF: '/staff',
    CREATE_STAFF: '/staff/create',
    TASKS: '/tasks',
    CREATE_TASK: '/tasks/create',
    EDIT_TASK: '/tasks/edit/:id',
    ISSUES: '/issues',
    CREATE_ISSUE: '/issues/create',
    EDIT_ISSUE: '/issues/edit/:id',
    PERMISSIONS: '/permissions',
    CREATE_PERMISSION: '/permissions/create',
    EDIT_PERMISSION: '/permissions/edit/:id',
    ROLES: '/roles',
    CREATE_ROLE: '/roles/create',
    EDIT_ROLE: '/roles/edit/:id',
    TASK_STATUS: '/task-status',
    CREATE_TASK_STATUS: '/task-status/create',
    EDIT_TASK_STATUS: '/task-status/edit/:id',
    PROJECTS: '/projects',
    CREATE_PROJECT: '/projects/create',
    EDIT_PROJECT: '/projects/edit/:id',
    TEAM: '/team',
    NOT_FOUND: '*',
};
